image: busybox

pages:
  stage: deploy
  environment: production
  script:
    - mkdir -p public
    - cp -r docs/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
